image: testing
test:
  tags:
    - testing-docker
  script:
    - testing
  artifacts:
    paths: [report.txt.enc]
    when: always
rk_01:
  image: gcc
  stage: build
  only:
      - rk_01
  script:
      - rk_01_01
      - gcc -Wall -Werror main.c
      - cat test01.txt | ./a.out 
rk_03:
  image: gcc
  stage: build
  only:
      - rk_03
 script:
     - cd rk_03
     - make build
     - make run
